channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.2
  - pytorch>=1.9.0
  - torchvision
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - torchvision
      - pytorch-lightning>=1.3.5

