channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.2
  - pytorch>=1.6.0
  - torchvision
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - cloudpickle==1.6.0
      - boto3
      - gorilla
      - pytorch_lightning>=1.0.2

