channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pip
- pip:
  - matplotlib
  - torch>=2.0
  - lightning>=2.0
  - jsonargparse[signatures]>=4.17.0
  - mlflow>=2.0
  - captum
  - webdataset
  - sklearn
  - torchvision>=0.15.1
