channels:
- defaults
- pytorch
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - captum
  - sklearn
  - transformers
  - portalocker
  - torch>=2.0
  - torchtext>=0.15.1
  - lightning>=2.0
  - torchvision>=0.15.1
  - jsonargparse[signatures]>=4.17.0
  - torchdata
