channels:
- defaults
- pytorch
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - captum
  - sklearn
  - transformers
  - torch>=1.9.0
  - torchtext>=0.10.0
  - pytorch-lightning>=1.4.0
  - torchvision>=0.10.0
  - deepspeed
