channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pip
- pip:
  - torch>=2.0
  - jsonargparse[signatures]>=4.17.0
  - torchvision>=0.15.1
  - matplotlib
  - lightning>2.0
  - mlflow>=2.0
  - captum
